services:
  # The Flask Backend
  - type: web
    name: healthcare-api-service
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend app:app --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: FLASK_ENV
        value: production

  # The Angular Frontend
  - type: static
    name: healthcare-frontend-site
    runtime: node
    rootDir: angular-frontend
    buildCommand: npm install && npm run build
    publishPath: dist/angular-frontend/browser # Check your angular.json for the exact build path
    routes:
      - type: rewrite
        source: /*
        destination: /index.html